sudo: false
dist: trusty

language: php

php:
  - 7.3

branches:
  only:
    - master

cache:
  directories:
    - node_modules
    - vendor

before_script:
  - export XDEBUG_MODE=coverage
  - composer self-update
  - composer install --no-interaction

script:
  - composer phpcs
  - composer phpstan
  - composer phpunit
